---
name: Magento Module Test

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 1 * * *'

jobs:
  phpstan:
    name: PHPStan Magento Integration Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer:2.4.2
          php-version: 8.1
          extensions: mbstring, intl
          coverage: none

      - name: Install Composer dependencies
        working-directory: ./src/BitExpert_PHPStanTests
        run:
          composer install --no-interaction;

      - name: PHPStan version
        working-directory: ./src/BitExpert_PHPStanTests
        run:
          ./vendor/bin/phpstan --version

      - name: Run PHPStan
        working-directory: ./src/BitExpert_PHPStanTests
        run:
          ./vendor/bin/phpstan analyse

      - name: Run PHPStan (Bleeding Edge)
        working-directory: ./src/BitExpert_PHPStanTests
        run:
          ./vendor/bin/phpstan analyse -c bleedingEdge.neon
